# Generated by Django 4.1.2 on 2022-11-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contoso_university.department'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(null=True, to='contoso_university.course'),
        ),
    ]
