# Generated by Django 4.1.2 on 2022-11-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0002_alter_course_department_alter_instructor_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contoso_university.department'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='contoso_university.course'),
        ),
    ]
