# Generated by Django 4.1.2 on 2022-11-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0003_alter_course_department_alter_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
    ]
