# Generated by Django 4.1.2 on 2022-11-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0004_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeassignment',
            name='id',
        ),
        migrations.AlterField(
            model_name='officeassignment',
            name='instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contoso_university.instructor'),
        ),
    ]
