# Generated by Django 4.1.2 on 2022-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0007_courseassignment_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, through='contoso_university.CourseAssignment', to='contoso_university.course'),
        ),
    ]
