# Generated by Django 4.1.2 on 2022-11-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0008_instructor_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='team',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='team',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contoso_university.curriculum'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contoso_university.student'),
        ),
        migrations.DeleteModel(
            name='CourseAssignment',
        ),
        migrations.AddField(
            model_name='teamcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoso_university.course'),
        ),
        migrations.AddField(
            model_name='teamcourse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoso_university.team'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='team_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contoso_university.teamcourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='team_courses',
            field=models.ManyToManyField(blank=True, to='contoso_university.teamcourse'),
        ),
        migrations.AddField(
            model_name='student',
            name='team_courses',
            field=models.ManyToManyField(through='contoso_university.Enrollment', to='contoso_university.teamcourse'),
        ),
        migrations.AddField(
            model_name='team',
            name='courses',
            field=models.ManyToManyField(through='contoso_university.TeamCourse', to='contoso_university.course'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('team_course', 'student')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
