# Generated by Django 4.1.2 on 2022-11-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoso_university', '0009_teamcourse_remove_course_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='contoso_university.team'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teamcourse',
            unique_together={('course', 'team')},
        ),
    ]
