# Generated by Django 4.1.2 on 2022-10-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_team_current_task_worker_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='team',
            name='workers',
            field=models.ManyToManyField(related_name='teams', to='tasks.worker'),
        ),
    ]
