# Generated by Django 4.1.2 on 2022-10-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_team_alter_team_current_task_alter_team_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notgroup',
            fields=[
                ('groupid', models.AutoField(db_column='GroupId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
            ],
            options={
                'db_table': 'NotGroup',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=32, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=36, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Groupuser',
            fields=[
                ('groupid', models.ForeignKey(db_column='GroupId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tasks.notgroup')),
                ('userid', models.ForeignKey(blank=True, db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.user')),
            ],
            options={
                'db_table': 'GroupUser',
                'unique_together': {('groupid', 'userid')},
            },
        ),
    ]
